---
- name: Install Python
  raw: which python || (sudo yum install -y centos-release-scl && sudo yum install -y python)
  register: python_check
  changed_when: not python_check.stdout is search('/bin/python')
 
- name: Import EPEL GPG key.
  rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: Enable EPEL repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    enabled: yes

- name: Install pip
  yum:
    name: python-pip
    state: present
    update_cache: yes