---
- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Python3
  raw: which python3 || sudo apt-get update && sudo apt-get install -qq -y python-simplejson
  register: python_check
  changed_when: not python_check.stdout is search('/usr/bin/python3')

- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes